# Site settings
title: Bashy
logo_url: /assets/bashy.svg
permalink: /news/:year/:month/:day/:title/
claim: "Taking care of the People in OpenSource"
description: > # this means to ignore newlines until "baseurl:"
  OpenSource is the giant all of modern tech is standing on. At Bashy we provide services and products to keep this giant up, fit and healthy. On top we improve it wherever we can – making sure the human doesn't fall short of technology.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bashy.io" # the base hostname & protocol for your site
twitter_username: bashyHQ
github_username:  bashyHQ
contact_email: " ben at create-build-execute dot com"
# Build settings
markdown: kramdown

hero_image: http://c1.staticflickr.com/5/4046/4333386510_89928d2553_b.jpg

mailchimp:
  server: bashy.us12.list-manage.com
  user: 78092809e918ff81694633576
  id: 2113bfe5cb
